// This file is generated by Sim IDX. Do not edit manually.
import { pgEnum, pgTable as table } from "drizzle-orm/pg-core";
import * as t from "drizzle-orm/pg-core";
import { db, types } from "@duneanalytics/sim-idx";

export const swap = table("swap", {
  chainId: db.uint64('chain_id'),
  txnHash: db.bytes32('txn_hash'),
  blockNumber: db.uint64('block_number'),
  blockTimestamp: db.uint64('block_timestamp'),
  makerToken: db.address('maker_token'),
  makerAmt: db.uint256('maker_amt'),
  makerTokenSymbol: t.text('maker_token_symbol'),
  makerTokenName: t.text('maker_token_name'),
  makerTokenDecimals: db.uint64('maker_token_decimals'),
  takerToken: db.address('taker_token'),
  takerAmt: db.uint256('taker_amt'),
  takerTokenSymbol: t.text('taker_token_symbol'),
  takerTokenName: t.text('taker_token_name'),
  takerTokenDecimals: db.uint64('taker_token_decimals'),
  txnOriginator: db.address('txn_originator'),
  maker: db.address('maker'),
  taker: db.address('taker'),
  reactor: db.address('reactor'),
})
